stages:
  - build
  - test
  - docker

before_script:
  - apt-get -qq update && apt-get install -qqy --no-install-recommends openconnect wget
  - openconnect nomade.etu.univ-nantes.fr --juniper --user=e21a432s -b < mdp.txt

build-job:       # Construction de l'image
  image: gradle:jdk11 # Départ d'une image gradle avec jdk version 11
  stage: build # L'étape de build
  before_script:
    - echo "Version de java"
    - which java
  script:
    - echo "Compilation du code et creation d'un jar"
    - ./gradlew build -x test # Build sans les tests
    - ./gradlew jar # Créer un jar
    - echo "Fin du build"


unit-test-job:   # Exécution des tests
  image: gradle:jdk11
  stage: test
  script:
    - echo "Exécution des tests"
    - ./gradlew build
    - ./gradlew test
    - echo "Fin des tests"


deploy-job: # Test build docker
  stage: docker
  services:
    - docker:dind # Docker in docker
  script:
    - echo "Build docker"
    - ./gradlew build
    - ./gradlew jar
    - docker build -t api-music. # Créer une image à partir du docker file
    - docker run --name container-music-api -d -p 9090:80 api-music # Lance un container avec l'aimge api-music
    - echo "Liste docker et container"
    - docker ps && docker image ls # Liste les images et container
    - echo "Docker déployé avec succes."
