stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - which java
    - echo "Compilation du code et creation d'un jar"
    - ./gradlew jar
    - ./gradlew build
    - echo "Fin du build"


unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Exécution des tests"
    - chmod +x vpn.sh
    - ./vpn.sh
    - ./gradlew test
    - echo "Fin des tests"


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Déploiement de l'application"
    - ./gradlew bootRun
    - echo "Application déployé avec succes."
