stages:
  - build
  - test
  - docker

build-job:       # Construction de l'image
  stage: build
  before_script:
    - echo "Version de java"
    - which java
  script:
    - echo "Compilation du code et creation d'un jar"
    - ./gradlew build
    - ./gradlew jar
    - echo "Fin du build"


unit-test-job:   # Exécution des tests
  stage: test    
  script:
    - echo "Exécution des tests"
    - ./gradlew build
    - ./gradlew test
    - echo "Fin des tests"


deploy-job: # Test build docker
  stage: docker
  services:
    - docker:dind
  script:
    - echo "Build docker"
    - ./gradlew build
    - ./gradlew jar
    - docker build -t api-music.
    - docker run --name container-music-api -d -p 9090:80 api-music
    - echo "Liste docker et container"
    - docker ps && docker image ls
    - echo "Docker déployé avec succes."
